name: Prevent Repl.it Coldstart

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: '*/15 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://service-ticketing-system-api.onrender.com/welcome/api"
        expected-statuses: "200,301"
  ping_site2:
    runs-on: ubuntu-latest
    name: Ping the site2
    steps:
    - name: Check the site
      id: hello
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://trippins.ayanavakarmakar.repl.co"
        expected-statuses: "200,301"
