name: Prevent Repl.it Coldstart

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  schedule:
    - cron: '*/9999 * * * *'

jobs:
  ping_site:
    runs-on: ubuntu-latest
    name: Ping the site
    steps:
    - name: Check site1
      id: site1
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://service-ticketing-system-api.onrender.com/welcome/api"
        expected-statuses: "200,301"
    - name: Check site2
      id: site2
      uses: srt32/uptime@master
      with:
        url-to-hit: "https://ayanava-karmakar.vercel.app"
        expected-statuses: "200,301"
  
